default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)

  app_name: "Polish cancer app"
  version: "0.1.0"
  
  data:
    config_file: !expr Sys.getenv("DATA_CONFIG_FILE", "config_data.yml")
    profile: !expr Sys.getenv("DATA_CONFIG_PROFILE", "pl_cancer_data")
